---
title: "Past Projects"
description: |
  Links to an older project site
author:
  - name: mxblsdl
date: 2022-01-30
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


The following are projects created with plain `HTML` and `JS` for a personal website that went largely unfinished. They are hosted through github and it never made sense to port them over to this site. These projects were just for fun when I discovered web development but I'm still happy with them years later.

### NBA Chart JS

[Link](https://mxblsdl.github.io/urls/nba_stats.html){target='_blank'}

Interactive chart made with Chart JS and data processing/web scraping with R. Compares NBA players on a couple different stats.


### NBA Map

[Link](https://mxblsdl.github.io/nba_fission/){target='_blank'}

![www/nba_chart_prev.jpg]

Interactive map of NBA arenas made entirely with JS. Data processing with R


### Radio Coverage

[Link](https://mxblsdl.github.io/urls/or_radio/){target='_blank'}

Recreation of a Carto DB map showing coverage for basketball radio stations in Oregon


### Voting Power

[Link](https://mxblsdl.github.io/urls/voting_power.html){target = '_blank'}

Exercise in Chart JS, Leaflet, and a little D3 showing relative voting power of different states


### CA Agriculture

[Link](https://mxblsdl.github.io/urls/ag.html){target='_blank'}

The beta interface to a biomass power study concerning agriculture in California. The details of the project can be hard to explain, but I think this is a nice use of Chart.js and leaflet to display data. 

This would eventually become the webtool seen [here](https://cbrec.schatzcenter.org/forest/forestry.html) although I was no longer working on the project when this was created.

